import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function convertAdminPropertyToPropertyType(property: AdminProperty): Property {
  return {
    id: property.id,
    title: property.title,
    description: property.description,
    price: property.price,
    location: property.location,
    propertyType: property.propertyType,
    status: property.status,
    bedrooms: property.bedrooms,
    bathrooms: property.bathrooms,
    area: property.area,
    features: property.features,
    images: property.images,
    createdAt: property.createdAt,
    updatedAt: property.updatedAt,
    unitTypeDetails: property.unitTypeDetails || null,
    unitType: property.unitType || null,
    unitNumber: property.unitNumber || null,
    floorNumber: property.floorNumber || null,
    buildingName: property.buildingName || null,
    developer: property.developer || null,
    yearBuilt: property.yearBuilt || null,
    parkingSpaces: property.parkingSpaces || null,
    furnishingStatus: property.furnishingStatus || null,
    availableUnits: property.availableUnits || null,
    totalUnits: property.totalUnits || null,
    maintenanceFee: property.maintenanceFee || null,
    propertyTax: property.propertyTax || null,
    insurance: property.insurance || null,
    amenities: property.amenities || [],
    nearbyAttractions: property.nearbyAttractions || [],
    propertyDocuments: property.propertyDocuments || [],
    virtualTourUrl: property.virtualTourUrl || null,
    mapLocation: property.mapLocation || null,
    contactInfo: property.contactInfo || null,
    viewingSchedule: property.viewingSchedule || null,
    priceHistory: property.priceHistory || [],
    propertyStatus: property.propertyStatus || null,
    listingAgent: property.listingAgent || null,
    propertyFeatures: property.propertyFeatures || [],
    propertyRules: property.propertyRules || [],
    propertyInsurance: property.propertyInsurance || null,
    propertyTaxInfo: property.propertyTaxInfo || null,
    propertyMaintenance: property.propertyMaintenance || null,
    propertyUtilities: property.propertyUtilities || null,
    propertySecurity: property.propertySecurity || null,
    propertyAccessibility: property.propertyAccessibility || null,
    propertySustainability: property.propertySustainability || null,
    propertyTechnology: property.propertyTechnology || null,
    propertyCommunity: property.propertyCommunity || null,
    propertyInvestment: property.propertyInvestment || null,
    propertyLegal: property.propertyLegal || null,
    propertyFinancial: property.propertyFinancial || null,
    propertyManagement: property.propertyManagement || null,
    propertyMarketing: property.propertyMarketing || null,
    propertyAnalytics: property.propertyAnalytics || null,
    propertyReports: property.propertyReports || [],
    propertyNotifications: property.propertyNotifications || [],
    propertySettings: property.propertySettings || null,
    propertyPreferences: property.propertyPreferences || null,
    propertyLimitations: property.propertyLimitations || [],
    propertyRequirements: property.propertyRequirements || [],
    propertyRestrictions: property.propertyRestrictions || [],
    propertyGuidelines: property.propertyGuidelines || [],
    propertyPolicies: property.propertyPolicies || [],
    propertyProcedures: property.propertyProcedures || [],
    propertyStandards: property.propertyStandards || [],
    propertyCriteria: property.propertyCriteria || [],
    propertyConditions: property.propertyConditions || [],
    propertyTerms: property.propertyTerms || [],
    propertyAgreements: property.propertyAgreements || [],
    propertyContracts: property.propertyContracts || [],
    propertyLeases: property.propertyLeases || [],
    propertyDeeds: property.propertyDeeds || [],
    propertyTitles: property.propertyTitles || [],
    propertyMortgages: property.propertyMortgages || [],
    propertyLoans: property.propertyLoans || [],
    propertyInsurance: property.propertyInsurance || null,
    propertyTaxInfo: property.propertyTaxInfo || null,
    propertyMaintenance: property.propertyMaintenance || null,
    propertyUtilities: property.propertyUtilities || null,
    propertySecurity: property.propertySecurity || null,
    propertyAccessibility: property.propertyAccessibility || null,
    propertySustainability: property.propertySustainability || null,
    propertyTechnology: property.propertyTechnology || null,
    propertyCommunity: property.propertyCommunity || null,
    propertyInvestment: property.propertyInvestment || null,
    propertyLegal: property.propertyLegal || null,
    propertyFinancial: property.propertyFinancial || null,
    propertyManagement: property.propertyManagement || null,
    propertyMarketing: property.propertyMarketing || null,
    propertyAnalytics: property.propertyAnalytics || null,
    propertyReports: property.propertyReports || [],
    propertyNotifications: property.propertyNotifications || [],
    propertySettings: property.propertySettings || null,
    propertyPreferences: property.propertyPreferences || null,
    propertyLimitations: property.propertyLimitations || [],
    propertyRequirements: property.propertyRequirements || [],
    propertyRestrictions: property.propertyRestrictions || [],
    propertyGuidelines: property.propertyGuidelines || [],
    propertyPolicies: property.propertyPolicies || [],
    propertyProcedures: property.propertyProcedures || [],
    propertyStandards: property.propertyStandards || [],
    propertyCriteria: property.propertyCriteria || [],
    propertyConditions: property.propertyConditions || [],
    propertyTerms: property.propertyTerms || [],
    propertyAgreements: property.propertyAgreements || [],
    propertyContracts: property.propertyContracts || [],
    propertyLeases: property.propertyLeases || [],
    propertyDeeds: property.propertyDeeds || [],
    propertyTitles: property.propertyTitles || [],
    propertyMortgages: property.propertyMortgages || [],
    propertyLoans: property.propertyLoans || [],
  };
}
